apiVersion: v1
kind: Service
metadata:
  name: back-service
  labels:
    app: backend
spec:
  type: ClusterIP
  selector:
    name: back-pod
  ports:
    - name: http-backend
      protocol: TCP
      port: 8080