apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-deployment
  labels:
    app: db
spec:
  replicas: 2
  selector:
    matchLabels:
      name: db-pod
  template:
    metadata: 
      labels: 
        name: db-pod
    spec: 
      containers:
      - name: db-container
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root