apiVersion: apps/v1
kind: Deployment
metadata:
  name: front-deployment
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      name: front-pod
  template:
    metadata: 
      labels: 
        name: front-pod
    spec: 
      containers:
      - name: front-container
        image: nginx:alpine