apiVersion: v1
kind: Service
metadata:
  name: front-service
  labels:
    app: frontend
spec:
  type: ClusterIP
  selector:
    name: front-pod
  ports:
    - name: http-frontend
      protocol: TCP
      port: 80