apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  template:
    spec: 
      containers:
      - name: proxy-container
        volumeMounts:
          - name: server-volume
            mountPath: /etc/nginx/conf.d
      volumes:
        - name: server-volume
          configMap:
            name: proxy-server
            items:
              - key: server
                path: default.conf